apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.dbRootPassword.secretName }}
  labels:
    app: {{ include "mychart.name" . }}
type: Opaque
data:
  password: {{ .Values.env.dbRootPassword.password | b64enc }}
