apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app: {{ include "mychart.name" . }}
spec:
  selector:
    app: {{ include "mychart.name" . }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
